jdk:
  - openjdk8
language: java
sudo: false

script:
  - mvn test
  - mvn cobertura:cobertura

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  slack: analogalexinc:SXEQeS09kKf2VdQfiDmMuJwN
